// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define WS2812_PWM_DRIVER PWMD4
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM7
#define WS2812_DMA_CHANNEL 7

#define FORCE_NKRO

#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define DYNAMIC_MACRO_NO_NESTING

#define MK_3_SPEED
#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 6
#define MK_C_OFFSET_1 4
#define MK_C_INTERVAL_1 8

#define LEADER_TIMEOUT 250
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT

#define ENCODER_DIRECTION_FLIP

#define RGB_MATRIX_LED_COUNT 68 
#define RGB_MATRIX_LED_PROCESS_LIMIT (RGB_MATRIX_LED_COUNT + 4) / 5

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BAND_VAL
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DEFAULT_HUE 170
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 255
#define RGB_MATRIX_DEFAULT_SPD 80 

/* for tmux send_string delays */
#    define TMUX_DELAY 8

/* monitored base layers for macos */
#    define CONFIG_MACOS_BASE_LAYERS { MAC_BASE }
#    define CONFIG_MACOS_BASE_LAYERS_COUNT 1
#    define CONFIG_DEFAULT_MAC_LAYR MAC_BASE
#    define CONFIG_DEFAULT_WIN_LAYR WIN_BASE

/* monitored base layers for macos */
#    define CONFIG_ALL_BASE_LAYERS { MAC_BASE, WIN_BASE }
#    define CONFIG_ALL_BASE_LAYERS_COUNT 2

/* key indexes that changed to shifted version when caps is used */
#    define CONFIG_CAPSLOCK_SHIFTED ((i > 42 && i < 53) || (i > 25 && i < 35) || (i > 13 && i < 21))
#    define CONFIG_CAPSWORD_EXTRA (i == 65)

/* keyfade settings */
#    define CONFIG_KEYFADE_START_DELAY 10
#    define CONFIG_KEYFADE_START_VAL 119
#    define CONFIG_KEYFADE_CALLBACK_INTERVAL 20

/* rgb_matrix_indicators_advanced_user settings */
#    define CONFIG_NO_RALT_KEY
#    define CONFIG_NO_RCMD_KEY
#    define CONFIG_RGB_LAYER_INDICATORS { I_INDICATOR, I_INDICATOR2}
#    define CONFIG_RGB_LAYER_INDICATORS_COUNT 2
#    define CONFIG_DEFAULT_INDICATOR_COLOR RGB_BLUE
#    define CONFIG_KEY_INDEX_MAX 67
#    define CONFIG_FN_LAYR_COLOR RGB_GREEN
#    define CONFIG_MREC_KEY_COLOR RGB_MAGENTA
#    define CONFIG_SHIFT_LAYR_COLOR RGB_ORANGE
#    define CONFIG_KCTL_LAYR_COLOR RGB_RED
#    define CONFIG_TMUX_LAYR_COLOR RGB_CYAN
#    define CONFIG_SYM_LAYR_COLOR RGB_BLUE
#    define CONFIG_WIDE_LAYR_COLOR RGB_PURPLE
#    define CONFIG_CIRC_LAYR_COLOR RGB_CORAL
#    define CONFIG_EMO_LAYR_COLOR RGB_YELLOW
#    define CONFIG_DEFUALT_LAYR_COLOR 0x77,0x77,0x77
#    define CONFIG_EXTRA_BASE_LAYR_COLORS \
     { \
         { I_CAPS, RGB_BLUE }, \
         { I_FN, RGB_BLUE }, \
         { I_TAB, 0x77,0x77,0x77 }, \
     }
#    define CONFIG_EXTRA_BASE_LAYR_COLORS_COUNT 3
#    define CONFIG_ACCENT_KEY_COLOR RGB_YELLOW
#    define CONFIG_CAPS_WORD_SHIFT_COLOR RGB_WHITE 
#    define CONFIG_HROWLIGHT_COLOR RGB_GREEN
#    define CONFIG_FJLIGHT_COLOR RGB_WHITE
#    define CONFIG_LEADER_COLORA RGB_TURQUOISE
#    define CONFIG_LEADER_COLORB RGB_CYAN
#    define CONFIG_KEYLIGHT_STD_COLOR RGB_WHITE
#    define CONFIG_EEPROM_RESET_DEFAULT_LAYER WIN_BASE
#    define CONFIG_EEPROM_RESET_DEFAULT_IS_LINUX
#    define CONFIG_LOCK_RESTORE_ANIMATION_FROM_SUSPEND_MS 25
//#    define CONFIG_LOCK_LAYR_EXTRA_FLASH_KEYS { I_ESC, I_ENT }
//#    define CONFIG_LOCK_LAYR_EXTRA_FLASH_KEYS_COUNT 2
//#    define CONFIG_LOCK_LAYR_EXTRA_FLASH_COLOR RGB_BLUE
