// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define WS2812_PWM_DRIVER PWMD4
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM7
#define WS2812_DMA_CHANNEL 7

#define FORCE_NKRO

#define TAPPING_TERM 250

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define DYNAMIC_MACRO_NO_NESTING

#define MK_3_SPEED
#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 6
#define MK_C_OFFSET_1 4
#define MK_C_INTERVAL_1 8

#define LEADER_TIMEOUT 200
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT

#define ENCODER_DIRECTION_FLIP

#define RGB_MATRIX_LED_COUNT 68 
#define RGB_MATRIX_LED_PROCESS_LIMIT (RGB_MATRIX_LED_COUNT + 4) / 5

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BAND_VAL
#define RGB_MATRIX_DEFAULT_HUE 170
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 220
#define RGB_MATRIX_DEFAULT_SPD 80 
